name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish artifacts for"
        required: true
  release:
    types:
      - published

permissions: {} # No permissions are granted at the workflow level

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set TAG_NAME
        id: vars
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name || inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Required to resolve tag commits

      - name: Resolve commit SHA for tag
        id: resolve_sha
        run: |
          COMMIT_SHA=$(git rev-list -n 1 $TAG_NAME)
          echo "COMMIT_SHA [$COMMIT_SHA]"
          echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        env:
          TAG_NAME: ${{ steps.vars.outputs.TAG_NAME }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@0bd50d53a6d7fb5cb921e607957e9cc12b4ce392 # v12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI.yml
          workflow_conclusion: success
          commit: ${{ steps.resolve_sha.outputs.commit-sha }}
          repo: ${{ github.repository }}
          name: ".+-packages"
          name_is_regexp: true

      - name: List downloaded files
        run: ls -1 -R *-packages

      - name: Upload release assets
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: ${{ steps.vars.outputs.TAG_NAME }}
          files: |
            *-packages/CTKAppLauncher-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.COMMONTKBOT_GITHUB_TOKEN }}
